spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dachpc_db
    username: dach123
    password: dach123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect