services:
  keycloak:
    image: "quay.io/keycloak/keycloak:latest"
    command:
      - start-dev
      - --http-port=8084
      - --import-realm
    restart: "on-failure"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8084:8084"
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: dach123
      POSTGRES_PASSWORD: dach123
      POSTGRES_DB: dachpc_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - dach_net

volumes:
  pg_data:
    driver: local

networks:
  dach_net:
    driver: bridge